DesignProject: BUILDING WITH RESPONSIVE DESIGN
webmarkyn/Responsive-Design pull request #2
Opened 2019-09-25 20:49 UTC by webmarkyn

2019-09-26 12:25 UTC, SunnyAsar requested changes
# Hello @webmarkyn  and @rkyankya 👋 
well done guys 😃 , we are well on our way to a wonderful project, lets just hit all the points and make it look exactly like [thenextweb.com](https://thenextweb.com/)
### lets add these:
* [ ] It contains sub-navigation row.
* [ ] It contains search icon at the rightmost side of sub-navigation row.

###### Medium version changes
* [ ] TWN logo appears at the leftmost part. (The logo is not always there)
###### Small version changes
* [ ] Navigation and sub-navigation row changes to a hamburger (bars) icon at the rightmost part (next to search icon).

##### Footer
* [ ] It contains social media icons vertically and horizontally aligned.
* [ ] It contains TNW logo with a copyright paragraph.


#### Finally
 Please look at the original site and the nav behaviour especially and make update accordingly.


**Make another review request when the updates are in place** Cheers!

2019-09-26 12:25 UTC, SunnyAsar commented on style.css
> +  background-position: center;
the link to your image assets doesn't match what's in the project. so its all blank:
![Screenshot 2019-09-26 at 1 10 10 PM](https://user-images.githubusercontent.com/10922508/65686944-07452e00-e05f-11e9-909f-9b19299bb068.png)

2019-09-26 12:25 UTC, SunnyAsar commented on style.css
> +@media only screen and (max-width: 655px) {
we need some media queries to handle the navigation especially, we should be displaying a hamburger icon for mobile

2019-09-26 12:25 UTC, SunnyAsar commented on index.html
> +            <input class="search-bar" type="text" placeholder="Search">
there is supposed to be  a sub nav here

2019-09-27 10:26 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-09-27 11:06 UTC, Torres-ssf requested changes
### Hi there team :hand: :smiley: 

Great work implementing the suggested changes. :clap: 
Your page looks really nice and you did a great job making it responsive :tada: 

**But we still have some change to make**
Notice that you need to do all REQUIRED changes in order to get this PR approved.

**[REQUIRED]**
- [ ]  There are some errors in your HTML code. Check them using this HTML [validator](https://validator.w3.org/) . Ignore the warnings.

Please kindly make these changes and submit for code review again. Happy coding :computer:

2019-09-27 11:06 UTC, Torres-ssf commented on index.html
> +  <section class="latest-news">
**[REQUIRED]**
- [ ] We need to fix the position of the latest news heading.
![Screenshot from 2019-09-27 07-38-20](https://user-images.githubusercontent.com/30977845/65763641-3f4d7f00-e0fa-11e9-86f9-a50fc404082d.png)

2019-09-27 11:06 UTC, Torres-ssf commented on index.html
> +        <header class="latest-story" id="latest-2">
[TIP]
Why did you use the header tag as a container for each latest news item here? :thinking: . As it said in the [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header), a `header` element is intended to usually contain the surrounding section's heading. A better approach is to use `article` tags instead for each item.

2019-09-27 11:06 UTC, Torres-ssf commented on index.html
> +
**[REQUIRED]**
- [ ] I notice that you forget to implement the Latest deals section. We need to fix this. Remember that we also need to make it resposive.
![Screenshot from 2019-09-27 07-35-31](https://user-images.githubusercontent.com/30977845/65763393-a7e82c00-e0f9-11e9-83af-208d59c5a289.png)

2019-09-27 11:06 UTC, Torres-ssf commented on README.md
> +This project was executed by Mark Baidebura and Kyankya Raymond students of Microverse.
**[REQUIRED]**
Great job creating a descriptive readme file. But it's also a best practice to add some styles to it. By doing that you are making it more easy to read and understand. And it also gives a professional look. Check out this [template](https://github.com/othneildrew/Best-README-Template) about creating awesome readme files.

2019-09-27 18:06 UTC, ebukaume commented
**Hi team** :hand: 

You have really done some great jobs here. But you missed some important requirements. :wink: 

1. Please always validate your HTML code [here](https://validator.w3.org) to save you time because we will always find any validation errors. Please fix the duplicate ID error [here](https://github.com/webmarkyn/Responsive-Design/blob/Design/index.html#L357) and [here](https://github.com/webmarkyn/Responsive-Design/blob/Design/index.html#L543)

2. Also, you can do better with your README file as @Torres-ssf pointed out earlier. You can look at this [nice example](https://github.com/othneildrew/Best-README-Template) and make your README more professional. Guys this is always the first thing visitors to your repo see, so it's important we keep it as professional as possible. :smile: 

Please submit another code review request after you have made these changes. :v:

2019-09-28 00:44 UTC, Torres-ssf requested changes
### Hello there team :hand: 

Great job validating your page and remove the errors :+1: 

But I noticed that you removed the most Latest Funding section from its place, duplicated it, and placed it in the Latest Deals section. I'm sorry but Microverse guidelines for this project require that the cloned page must have all sections from the original page. We TSE are not allowed to approve any projects that don't met the guidelines :cry:.

**[REQUIRED]**
- [ ] Let's bring the Latest funding back to its place and create Latest deals section.

Please kindly make this change and submit for code review again. 
Happy coding :computer:

2019-09-29 19:05 UTC, whiz25 requested changes
## Awesome job :+1: team
You are basically one step from completing this project. But before that, please make sure ```stickler``` checks pass.
Do that and send for another review. You can also slack me @whiz25 if you have a challenge doing that.

2019-09-29 19:50 UTC, whiz25 commented
Don't forget to remove the horizontal scrollbar from your page.

2019-10-02 13:28 UTC, stratospherique approved these changes
### Great work implementing the suggested changes :clap: . Your project is approved :heavy_check_mark: and you may merge to master :+1: :+1:

2019-10-04 14:23 UTC, merged